#!/bin/sh

mkdir -p opk
cp ./snes9x4d.dge opk/snes9x
cp ./snes9x.png opk/icon.png

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Snes9x4D
Comment=SNES Emulator
Exec=snes9x %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.rs90.desktop

mksquashfs ./opk snes9x_rs90.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
